# Generated by Django 6.0.3 on 2026-04-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("titulo_profissional", models.CharField(max_length=100)),
                ("foto_perfil", models.ImageField(upload_to="perfil/")),
                ("biografia", models.TextField()),
                ("link_linkedin", models.URLField(blank=True, null=True)),
                ("link_github", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
