# Generated by Django 6.0.3 on 2026-04-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ects_totais", models.IntegerField()),
                ("descricao", models.TextField()),
                ("link_plano_estudos", models.URLField()),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenciatura",
                        to="portfolio.perfil",
                    ),
                ),
            ],
        ),
    ]
