# Generated by Django 6.0.3 on 2026-04-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_licenciatura"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("link_pagina_pessoal", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
