# Generated by Django 6.0.3 on 2026-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_docente"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ects", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("ano_semestre", models.CharField(max_length=50)),
                (
                    "docentes",
                    models.ManyToManyField(related_name="ucs", to="portfolio.docente"),
                ),
                (
                    "licenciaturas",
                    models.ManyToManyField(
                        related_name="ucs", to="portfolio.licenciatura"
                    ),
                ),
            ],
        ),
    ]
