# Generated by Django 6.0.3 on 2026-04-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link_tecnologia", models.URLField(blank=True, null=True)),
                ("descricao", models.TextField()),
                ("nivel_interesse", models.IntegerField()),
            ],
        ),
    ]
