# Generated by Django 6.0.3 on 2026-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=100)),
                ("nivel_dominio", models.IntegerField()),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
