# Generated by Django 6.0.3 on 2026-04-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=100)),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="formacoes/"),
                ),
                ("link_certificado", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
