# Generated by Django 6.0.3 on 2026-04-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("sumario", models.TextField()),
                ("orientador", models.CharField(max_length=100)),
                ("classificacao", models.IntegerField()),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
