# Generated by Django 6.0.3 on 2026-04-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao_processo", models.TextField()),
                ("erros_resolucoes", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="making_of/"),
                ),
            ],
        ),
    ]
