# Generated by Django 6.0.3 on 2026-04-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_competencia_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="perfil",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="making_ofs",
                to="portfolio.perfil",
            ),
        ),
    ]
