# Generated by Django 6.0.3 on 2026-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_makingof_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="ano",
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_imagem",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
