# Generated by Django 6.0.3 on 2026-04-02 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_tfc_ano_tfc_link_imagem_tfc_link_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenciatura",
            name="perfil",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenciatura",
                to="portfolio.perfil",
            ),
        ),
    ]
