# Generated by Django 6.0.3 on 2026-04-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_alter_licenciatura_perfil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="ano_semestre",
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="ano",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="bibliografia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo",
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="conteudos",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="metodologia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.IntegerField(default=1),
        ),
    ]
