# Generated by Django 6.0.3 on 2026-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_remove_unidadecurricular_ano_semestre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="ano_realizacao",
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name="projeto",
            name="link_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
