# Generated by Django 6.0.3 on 2026-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_projeto_ano_realizacao_projeto_link_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="perfil/"),
        ),
    ]
