# Generated by Django 6.0.5 on 2026-05-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_tipotecnologia_tecnologia_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
