# Generated by Django 6.0.5 on 2026-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_alter_tfc_palavras_chave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="nome",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(max_length=500),
        ),
    ]
